#!/bin/sh
mkdir -p "${DESTDIR}/usr/share/fonts/opentype"
mkdir -p "${DESTDIR}/usr/share/fonts/truetype"
cp -rf "/usr/share/fonts/opentype/fira" "${DESTDIR}/usr/share/fonts/opentype/"
cp -rf "/usr/share/fonts/truetype/roboto-slab" "${DESTDIR}/usr/share/fonts/truetype/"
fc-cache -s -y "${DESTDIR}" > /dev/null 2>&1
exit 0
